name: Release

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: make all
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.branch === 'main'
        with:
          files: |
            ./build/*
