name: "release"

on:
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: make all
      - run: |
          PACKAGE_VERSION=$(cat './node_modules/@elwood-studio/cli/package.json' | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo "pkg_version=$PACKAGE_VERSION" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.pkg_version }}"
          prerelease: false
          files: |
            ./dist/**/*
